Improve pre-build script error handling
Update pre-build script check to exit with error if not found.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,7 +43,14 @@ jobs:
         fi
 
     - name: Run custom pre-build script
-      run: '[[ -f pre-build.sh ]] && . pre-build.sh || :'
+      run: 'if [[ ! -f pre-build.sh ]]; then
+    echo "::error::pre-build.sh NOT FOUND"
+    exit 1
+fi
+
+echo "===== STARTING pre-build.sh ====="
+bash pre-build.sh
+echo "===== pre-build.sh FINISHED OK ====="'
 
     - name: Build firmware
       run: |
